apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-database-config
data:
  0-billing-setup.sql: |
    CREATE DATABASE orders;

    \c orders

    CREATE TABLE IF NOT EXISTS orders (
        id SERIAL PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL,
        number_of_items INTEGER NOT NULL,
        total_amount DECIMAL(10,2) NOT NULL
    );
  1-configure-postgres.sh: |
    #!/bin/bash
    set -e

    PGPASSWORD=$(cat /run/secrets/pgpassword)

    # Ensure the script is executable
    chmod +x /docker-entrypoint-initdb.d/1-configure-postgres.sh

    # Create the SQL file with the password change command
    echo "ALTER USER postgres WITH PASSWORD '$PGPASSWORD';" > /docker-entrypoint-initdb.d/change_password.sql

    # Run the SQL file as the postgres user
    psql -U postgres -f /docker-entrypoint-initdb.d/change_password.sql

    # Clean up by removing the SQL file
    rm /docker-entrypoint-initdb.d/change_password.sql
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: billing-database-config
