apiVersion: v1                     # Specifies the API version for the Service
kind: Service                      # Specifies the type of Kubernetes object
metadata:
  name: billing-database           # Name of the Service object
  labels:
    app: billing-database          # Labels for categorizing the Service
spec:
  ports:
  - port: 5432                     # Port exposed by the Service
    name: postgres                 # Name of the port
  clusterIP: None                  # No cluster IP, service acts as a headless service
  selector:
    app: billing-database          # Selector to match pods with the specified label

# - **apiVersion:** Specifies the API version for the Service.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name and labels.
# - **spec:** Defines the desired state of the Service.
#   - **ports:** List of ports that the Service exposes.
#     - **port:** Port exposed by the Service.
#     - **name:** Name of the port (postgres).
#   - **clusterIP:** Set to None, making the service headless.
#   - **selector:** Criteria to match the pods for the Service.