apiVersion: v1                        # Specifies the API version for the PersistentVolumeClaim
kind: PersistentVolumeClaim           # Specifies the type of Kubernetes object
metadata:
  name: billing-database-pvc          # Name of the PersistentVolumeClaim object
spec:
  accessModes:
    - ReadWriteOnce                   # Access mode, allows read/write by a single node
  resources:
    requests:
      storage: 100Mi                  # Requested storage capacity

# - **apiVersion:** Specifies the API version for the PersistentVolumeClaim.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name.
# - **spec:** Defines the desired state of the PersistentVolumeClaim.
#   - **accessModes:** Lists the access modes (ReadWriteOnce allows read/write by a single node).
#   - **resources:** Specifies the resource requests.
#     - **requests:** Details the specific resource request.
#       - **storage:** Requested storage capacity.