apiVersion: apps/v1                        # Specifies the API version for the Deployment
kind: Deployment                           # Specifies the type of Kubernetes object
metadata:
  name: inventory-app-deployment           # Name of the Deployment object
  labels:
    app: inventory-app                     # Labels for categorizing the Deployment
spec:
  replicas: 1                              # Number of desired pod replicas
  selector:
    matchLabels:
      app: inventory-app                   # Selector to match pods with the specified label
  template:
    metadata:
      labels:
        app: inventory-app                 # Labels applied to the pod template
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent1-node-3d90d0c5  # Node selector to schedule pods on a specific node
      containers:
      - name: inventory-app                # Name of the container
        image: danilocangucu/inventory-app:latest  # Docker image to use for the container
        ports:
        - containerPort: 8080              # Port that the container exposes
        resources:
          requests:
            cpu: "250m"                    # Minimum CPU requested
          limits:
            cpu: "500m"                    # Maximum CPU limit
        env:
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: PGDATABASE              # Environment variable sourced from a Secret
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: PGUSER                  # Environment variable sourced from a Secret
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: PGPASSWORD              # Environment variable sourced from a Secret
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: PGPORT                  # Environment variable sourced from a Secret
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: PGHOST                  # Environment variable sourced from a Secret
        - name: INVENTORY_PORT
          valueFrom:
            secretKeyRef:
              name: inventory-app-secret
              key: INVENTORY_PORT           # Environment variable sourced from a Secret
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/inventory-app  # Mounts a volume to the specified path
      volumes:
      - name: log-volume
        emptyDir: {}                       # Defines an empty directory volume

# - **apiVersion:** Specifies the API version for the Deployment.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name and labels.
# - **spec:** Defines the desired state of the Deployment.
#   - **replicas:** Number of desired pod replicas.
#   - **selector:** Criteria to match the pods for the Deployment.
#   - **template:** Template for creating pods.
#     - **metadata:** Labels applied to the pod template.
#     - **spec:** Pod specification.
#       - **nodeSelector:** Specifies the node to run the pod.
#       - **containers:** List of containers in the pod.
#         - **name:** Name of the container.
#         - **image:** Docker image for the container.
#         - **ports:** Ports exposed by the container.
#         - **resources:** Resource requests and limits for the container.
#         - **env:** Environment variables sourced from Secrets.
#         - **volumeMounts:** Volumes to mount inside the container.
#       - **volumes:** Volumes available to the pod, such as an empty directory.