apiVersion: v1
kind: Secret
metadata:
  name: inventory-app-secret
  namespace: default
type: Opaque
data:
  PGDATABASE: bW92aWVz # movies base64 encoded
  PGUSER: cG9zdGdyZXM=  # postgres base64 encoded
  PGPASSWORD: dDNzdA==  # t3st base64 encoded
  PGHOST: MTAuNDIuMy4xNDQ=
  PGPORT: NTQzMg==  # 5432 base64 encoded
  INVENTORY_PORT: ODA4MA==  # 8080 base64 encoded

