apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent1-node-3d90d0c5
      containers:
      - name: api-gateway
        image: danilocangucu/api-gateway:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:
        - name: NODE_USER
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: NODE_USER
        - name: GATEWAY_PORT
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: GATEWAY_PORT
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: RABBITMQ_URL
        - name: RABBITMQ_QUEUE
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: RABBITMQ_QUEUE
        - name: INVENTORY_API_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: INVENTORY_API_URL
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_USER_PWD
          valueFrom:
            secretKeyRef:
              name: api-gateway-secret
              key: RABBITMQ_USER_PWD
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/api-gateway
      volumes:
      - name: log-volume
        emptyDir: {}
