apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
type: Opaque
data:
  NODE_USER: bm9kZQ==  # node base64 encoded
  GATEWAY_PORT: MzAwMA==  # 3000 base64 encoded
  RABBITMQ_URL: YW1xcDovL2RhbmlsbzpkYW4xMjM0QDEwLjQyLjMuNzg6NTY3Mg==
  RABBITMQ_QUEUE: YmlsbGluZ19xdWV1ZQ==  # billing_queue base64 encoded
  INVENTORY_API_URL: aHR0cDovL2ludmVudG9yeS1hcHA6ODA4MC9tb3ZpZXM=  # http://inventory-app:8080/movies base64 encoded
  RABBITMQ_USER: ZGFuaWxv  # danilo base64 encoded
  RABBITMQ_USER_PWD: ZGFuMTIzNA==  # dan1234 base64 encoded
