apiVersion: v1                # Specifies the API version for the Secret
kind: Secret                  # Specifies the type of Kubernetes object
metadata:
  name: api-gateway-secret    # Name of the Secret object
  namespace: default          # Namespace where the Secret is created
type: Opaque                  # Indicates the Secret contains arbitrary user-defined data
data:
  NODE_USER: bm9kZQ==  # node base64 encoded
  GATEWAY_PORT: MzAwMA==  # 3000 base64 encoded
  RABBITMQ_URL: YW1xcDovL2RhbmlsbzpkYW4xMjM0QDo1Njcy
  RABBITMQ_QUEUE: YmlsbGluZ19xdWV1ZQ==  # billing_queue base64 encoded
  INVENTORY_API_URL: aHR0cDovLzEwLjQzLjc4LjE1Mzo4MDgwL21vdmllcw==
  RABBITMQ_USER: ZGFuaWxv  # danilo base64 encoded
  RABBITMQ_USER_PWD: ZGFuMTIzNA==  # dan1234 base64 encoded

# - **apiVersion:** Specifies the API version for the Secret.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name and namespace.
# - **type:** Indicates the type of data in the Secret (Opaque means arbitrary user-defined data).
# - **data:** Holds key-value pairs where the values are base64 encoded.