apiVersion: v1
kind: Service
metadata:
  name: billing-app-service
  labels:
    app: billing-app
spec:
  selector:
    app: billing-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  clusterIP: None