apiVersion: v1
kind: Secret
metadata:
  name: billing-app-secret
  namespace: default
type: Opaque
data:
  NODE_USER: bm9kZQ==  # node base64 encoded
  BILLING_PORT: ODA4MA==  # 8080 base64 encoded
  RABBITMQ_URL: YW1xcDovL2RhbmlsbzpkYW4xMjM0QDEwLjQyLjMuMTM4OjU2NzI=
  RABBITMQ_QUEUE: YmlsbGluZ19xdWV1ZQ==  # billing_queue base64 encoded
  PG_2_DATABASE: b3JkZXJz  # orders base64 encoded
  PG_2_USER: cG9zdGdyZXM=  # postgres base64 encoded
  PG_2_PASSWORD: dDNzdA==  # t3st base64 encoded
  PGHOST: MTAuNDIuMy4xNDA=
  PGPORT: NTQzMg==  # 5432 base64 encoded
