apiVersion: v1                # Specifies the API version for the Service
kind: Service                 # Specifies the type of Kubernetes object
metadata:
  name: billing-app-service   # Name of the Service object
  labels:
    app: billing-app          # Labels for categorizing the Service
spec:
  selector:
    app: billing-app          # Selector to match pods with the specified label
  ports:
  - protocol: TCP             # Protocol used by the Service
    port: 8080                # Port exposed by the Service
    targetPort: 8080          # Port on the pod that the Service forwards traffic to
  clusterIP: None             # No cluster IP, service acts as a headless service

# - **apiVersion:** Specifies the API version for the Service.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name and labels.
# - **spec:** Defines the desired state of the Service.
#   - **selector:** Criteria to match the pods for the Service.
#   - **ports:** List of ports that the Service exposes.
#     - **protocol:** Protocol used (TCP in this case).
#     - **port:** Port exposed by the Service.
#     - **targetPort:** Port on the pod that the Service forwards traffic to.
#   - **clusterIP:** Set to None, making the service headless.