apiVersion: v1                # Specifies the API version
kind: Secret                  # Specifies the type of Kubernetes object
metadata:
  name: billing-app-secret    # Name of the Secret object
  namespace: default          # Namespace where the Secret is created
type: Opaque                  # Indicates the Secret contains arbitrary user-defined data
data:
  NODE_USER: bm9kZQ==         # Encoded username for the node application
  BILLING_PORT: ODA4MA==      # Encoded billing application port (8080)
  RABBITMQ_URL: YW1xcDovL2RhbmlsbzpkYW4xMjM0QDo1Njcy  # Encoded URL for RabbitMQ
  RABBITMQ_QUEUE: YmlsbGluZ19xdWV1ZQ==  # Encoded RabbitMQ queue name (billing_queue)
  PG_2_DATABASE: b3JkZXJz     # Encoded PostgreSQL database name (orders)
  PG_2_USER: cG9zdGdyZXM=     # Encoded PostgreSQL username (postgres)
  PG_2_PASSWORD: dDNzdA==     # Encoded PostgreSQL password (t3st)
  PGHOST: MTAuNDIuMy4xNTU=    # Encoded PostgreSQL host
  PGPORT: NTQzMg==            # Encoded PostgreSQL port (5432)