apiVersion: v1                         # Specifies the API version for the Secret
kind: Secret                           # Specifies the type of Kubernetes object
metadata:
  name: inventory-database-secret      # Name of the Secret object
type: Opaque                           # Indicates the Secret contains arbitrary user-defined data
data:
  postgres-user: cG9zdGdyZXM=          # Encoded PostgreSQL username (postgres)
  postgres-password: dDNzdA==          # Encoded PostgreSQL password (t3st)

# - **apiVersion:** Specifies the API version for the Secret.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name.
# - **type:** Indicates the type of data in the Secret (Opaque means arbitrary user-defined data).
# - **data:** Holds key-value pairs where the values are base64 encoded.