apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-database-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/inventory-database
