apiVersion: v1                          # Specifies the API version for the PersistentVolume
kind: PersistentVolume                  # Specifies the type of Kubernetes object
metadata:
  name: inventory-database-pv           # Name of the PersistentVolume object
spec:
  capacity:
    storage: 100Mi                      # Total storage capacity of the volume
  accessModes:
    - ReadWriteOnce                     # Access mode, allows read/write by a single node
  hostPath:
    path: /mnt/data/inventory-database  # Host path on the node where the volume is mounted

# - **apiVersion:** Specifies the API version for the PersistentVolume.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name.
# - **spec:** Defines the desired state of the PersistentVolume.
#   - **capacity:** Specifies the storage capacity.
#   - **accessModes:** Lists the access modes (ReadWriteOnce allows read/write by a single node).
#   - **hostPath:** Specifies the path on the host node where the volume is mounted.