apiVersion: v1
kind: Secret
metadata:
  name: inventory-database-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM= # postgres (base64 encoded)
  postgres-password: dDNzdA== # t3st (base64 encoded)
