apiVersion: v1
kind: Service
metadata:
  name: inventory-database
  labels:
    app: inventory-database
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: inventory-database
