apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent1-node-3d90d0c5
      containers:
      - name: rabbitmq
        image: danilocangucu/rabbitmq:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_USER_PWD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_USER_PWD
