apiVersion: v1                    # Specifies the API version for the Service
kind: Service                     # Specifies the type of Kubernetes object
metadata:
  name: rabbitmq-service          # Name of the Service object
spec:
  selector:
    app: rabbitmq                 # Selector to match pods with the specified label
  ports:
  - protocol: TCP                 # Protocol used by the Service
    port: 5672                    # Port exposed by the Service
    targetPort: 5672              # Port on the pod that the Service forwards traffic to

# - **apiVersion:** Specifies the API version for the Service.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name.
# - **spec:** Defines the desired state of the Service.
#   - **selector:** Criteria to match the pods for the Service.
#   - **ports:** List of ports that the Service exposes.
#     - **protocol:** Protocol used (TCP in this case).
#     - **port:** Port exposed by the Service.
#     - **targetPort:** Port on the pod that the Service forwards traffic to.