apiVersion: v1                      # Specifies the API version for the Secret
kind: Secret                        # Specifies the type of Kubernetes object
metadata:
  name: rabbitmq-secret             # Name of the Secret object
  namespace: default                # Namespace where the Secret is created
type: Opaque                        # Indicates the Secret contains arbitrary user-defined data
data:
  RABBITMQ_USER: ZGFuaWxv           # Encoded RabbitMQ username (danilo)
  RABBITMQ_USER_PWD: ZGFuMTIzNA==   # Encoded RabbitMQ password (dan1234)

# - **apiVersion:** Specifies the API version for the Secret.
# - **kind:** Defines the type of Kubernetes object.
# - **metadata:** Contains metadata about the object, including name and namespace.
# - **type:** Indicates the type of data in the Secret (Opaque means arbitrary user-defined data).
# - **data:** Holds key-value pairs where the values are base64 encoded.